### ISSUE TITLE
催更一波！！！

### ISSUE THREAD

**Issue by baici1** [chai2010/ugo-compiler-book#6]
感觉很有意思，催更催更！！！

**Comment by baici1** [comment]
能不能在 README 上写关于学习资料啊。我也想跟着学习一波！！！！🤣🤣🤣

**Comment by chai2010** [comment]
刚更了 ch3.3 。
资料很多，主要是集中在 Go-ast-book、LLVM-IR 语法、一些基础的编译概念。
但 less is more，资料收集越多越累赘，还不如先一套王八拳实战到底
